name: Release
on:
  push:
    tags: ["v*.*.*"]
jobs:
  CI:
    uses: ./.github/workflows/ci.yml
  publish:
    name: Publish to PyPI
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install flit
        run: pip install flit~=3.7
      - name: Build and publish
        run: flit publish
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_KEY }}
