name: Check format, lint, type-check #, run tests
on: [push, pull_request]
jobs:
  check-format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: excitedleigh/setup-nox@v2.1.0
      - run: nox -s check_format
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: excitedleigh/setup-nox@v2.1.0
      - run: nox -s lint
  type-check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: excitedleigh/setup-nox@v2.1.0
      - run: nox -s mypy
  # tests:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       venv_version: ["3.9", "3.10", "3.11"]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: excitedleigh/setup-nox@v2.1.0
  #     - if: matrix.venv_version == '3.11'
  #       uses: actions/setup-python@v3.1.2
  #       with:
  #         python-version: "3.11-dev"
  #     - run: nox -s test-${{ matrix.venv_version }} --error-on-missing-interpreters
